---
- name: Start or stop service on remote systems
  hosts: all
  become: yes
  tasks:
    - name: Start or stop service
      service:
        name: "{{ service_location.split('/')[-1] }}"
        state: "{{ service_state }}"
